In [2]:
import numpy as np

In [3]:
a = np.array ([[2, 2, 1],
               [1, -1 , 1],
               [3, 2, -2]], dtype=float)

b = np.array([3, 4, 2], dtype = float)
n = len(b)
print("Augmentasi Matriks: \n", np.column_stack((a,b)))

#Eliminasi gauss untuk membentuk matriks segitiga atas
for k in range(n):
    
    if a[k,k] == 0:
        for i in range(k, len(b)):
            if a[i, k] != 0:
                a[[k, i]] = a[[i, k]]
                b[[k, i]] = b[[i, k]]
                break
            
    pivot = a [k, k]
    if pivot == 0:
        raise ValueError("Sistem tidak memiliki solusi unit atau tak terdeteksi.")
    
    a[k,:] /= pivot
    c[k] /= pivot
    
    for i in range(k+1, n):
        factor = a[i, k]
        a[i, k:] -= faktor * a [k, k]
        b[i] -= factor * b[k]
        
print("Matriks setelah eliminasi Gauss: ")
print(np.column_stack((a, b)))

#Substitusi mundur untuk mendapat hasil
x = np.zeros(n)
x[-1] = b[-1] / a[-1, -1]

for i in range(n-2, -1, -1):
    sum_val = b[i] - np.dot(a[i, i+1:], x[i+1])
    x[i] = sum_val / a[i, i]
    
print("Sulusi")
for i in range(len(x)):
    print("x%d = %.4f" % (i+1, x[i]))

Augmentasi Matriks: 
 [[ 2.  2.  1.  3.]
 [ 1. -1.  1.  4.]
 [ 3.  2. -2.  2.]]


NameError: name 'c' is not defined